/**
 * The CSV template offered in the import dialog.
 *
 * Every value here is invented, and recognisably so — `MUSTER`, `BEISPIEL`,
 * `.invalid` domains, which can never resolve. Real partner data must never
 * enter this repository, in any file (`docs/data-protection.md`, § 1).
 */

const HEADERS = [
  'Firmenname',
  'Handelsname',
  'Beziehungsrichtung',
  'Unternehmensebene',
  'Leistung',
  'Land',
  'Bundesland',
  'Ort',
  'PLZ',
  'Radius',
  'Ansprechpartner',
  'E-Mail',
  'Telefon',
  'Website',
  'Verfügbare Mitarbeiter',
  'Verfügbar ab',
  'Eigene Mitarbeiter',
  'Weitere Untervergabe',
  'Datacenter-Erfahrung',
  'Partnerstatus',
  'Verifizierungsstatus',
  'Sucht Subunternehmer',
  'Signaltyp',
  'Projekt',
  'Quelle',
  'Quellen-URL',
  'Letzter Kontakt',
  'Wiedervorlage',
  'Notiz',
];

const ROWS = [
  [
    'Muster Wachdienst GmbH',
    'Muster Security',
    'Kann für uns arbeiten',
    'Nachunternehmer',
    'Sicherheitsdienst',
    'DE',
    'Musterland',
    'Musterstadt',
    '00000',
    '50',
    'Muster Person',
    'kontakt@muster-wachdienst.invalid',
    '+49 000 0000000',
    'muster-wachdienst.invalid',
    '12',
    '01.09.2026',
    'Ja',
    'Nein',
    'Ja',
    'Interessent',
    'Selbst angegeben',
    'Nein',
    '',
    '',
    'Telefonat Muster',
    '',
    '01.08.2026',
    '01.10.2026',
    'Beispielhafter Eintrag — bitte durch eigene Daten ersetzen.',
  ],
  [
    'Beispiel Bau AG',
    '',
    'Sucht Subunternehmer',
    'Hauptunternehmer',
    'Bauunterstützung',
    'DE',
    'Musterland',
    'Beispielstadt',
    '00000',
    '',
    'Beispiel Person',
    'einkauf@beispiel-bau.invalid',
    '',
    'beispiel-bau.invalid',
    '',
    '',
    'Gemischt',
    'Ja',
    'Nein',
    'Kontaktiert',
    'Ungeprüft',
    'Ja',
    'Sucht Sicherheitsdienst',
    'Musterprojekt Nord',
    'Website des Unternehmens',
    'https://beispiel-bau.invalid/karriere',
    '15.08.2026',
    '15.09.2026',
    'Beispielhafter Eintrag — bitte durch eigene Daten ersetzen.',
  ],
];

export const PARTNER_IMPORT_TEMPLATE_CSV = [
  HEADERS.join(';'),
  ...ROWS.map((row) => row.join(';')),
].join('\r\n');
